name: Print vars
on:
  workflow_dispatch:

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Show version
        run: |
          echo "${{ env.GITHUB_REF_NAME }}"
      - name: Print vars
        run: |
          echo "CI : ${{ env.CI }}"
          echo "GITHUB_ACTION : ${{ env.GITHUB_ACTION }}"
          echo "GITHUB_ACTION_PATH : ${{ env.GITHUB_ACTION_PATH }}"
          echo "GITHUB_ACTION_REPOSITORY : ${{ env.GITHUB_ACTION_REPOSITORY }}"
          echo "GITHUB_ACTIONS : ${{ env.GITHUB_ACTIONS }}"
          echo "GITHUB_ACTOR : ${{ env.GITHUB_ACTOR }}"
          echo "GITHUB_ACTOR_ID : ${{ env.GITHUB_ACTOR_ID }}"
          echo "GITHUB_API_URL : ${{ env.GITHUB_API_URL }}"
          echo "GITHUB_BASE_REF : ${{ env.GITHUB_BASE_REF }}"
          echo "GITHUB_ENV : ${{ env.GITHUB_ENV }}"
          echo "GITHUB_EVENT_NAME : ${{ env.GITHUB_EVENT_NAME }}"
          echo "GITHUB_EVENT_PATH : ${{ env.GITHUB_EVENT_PATH }}"
          echo "GITHUB_GRAPHQL_URL : ${{ env.GITHUB_GRAPHQL_URL }}"
          echo "GITHUB_HEAD_REF : ${{ env.GITHUB_HEAD_REF }}"
          echo "GITHUB_JOB : ${{ env.GITHUB_JOB }}"
          echo "GITHUB_PATH : ${{ env.GITHUB_PATH }}"
          echo "GITHUB_REF : ${{ env.GITHUB_REF }}"
          echo "GITHUB_REF_NAME : ${{ env.GITHUB_REF_NAME }}"
          echo "GITHUB_REF_PROTECTED : ${{ env.GITHUB_REF_PROTECTED }}"
          echo "GITHUB_REF_TYPE : ${{ env.GITHUB_REF_TYPE }}"
          echo "GITHUB_REPOSITORY : ${{ env.GITHUB_REPOSITORY }}"
          echo "GITHUB_REPOSITORY_ID : ${{ env.GITHUB_REPOSITORY_ID }}"
          echo "GITHUB_REPOSITORY_OWNER : ${{ env.GITHUB_REPOSITORY_OWNER }}"
          echo "GITHUB_REPOSITORY_OWNER_ID : ${{ env.GITHUB_REPOSITORY_OWNER_ID }}"
          echo "GITHUB_RETENTION_DAYS : ${{ env.GITHUB_RETENTION_DAYS }}"
          echo "GITHUB_RUN_ATTEMPT : ${{ env.GITHUB_RUN_ATTEMPT }}"
          echo "GITHUB_RUN_ID : ${{ env.GITHUB_RUN_ID }}"
          echo "GITHUB_RUN_NUMBER : ${{ env.GITHUB_RUN_NUMBER }}"
          echo "GITHUB_SERVER_URL : ${{ env.GITHUB_SERVER_URL }}"
          echo "GITHUB_SHA : ${{ env.GITHUB_SHA }}"
          echo "GITHUB_STEP_SUMMARY : ${{ env.GITHUB_STEP_SUMMARY }}"
          echo "GITHUB_WORKFLOW : ${{ env.GITHUB_WORKFLOW }}"
          echo "GITHUB_WORKFLOW_REF : ${{ env.GITHUB_WORKFLOW_REF }}"
          echo "GITHUB_WORKFLOW_SHA : ${{ env.GITHUB_WORKFLOW_SHA }}"
          echo "GITHUB_WORKSPACE : ${{ env.GITHUB_WORKSPACE }}"
          echo "RUNNER_ARCH : ${{ env.RUNNER_ARCH }}"
          echo "RUNNER_DEBUG : ${{ env.RUNNER_DEBUG }}"
          echo "RUNNER_NAME : ${{ env.RUNNER_NAME }}"
          echo "RUNNER_OS : ${{ env.RUNNER_OS }}"
          echo "RUNNER_TEMP : ${{ env.RUNNER_TEMP }}"
          echo "RUNNER_TOOL_CACHE : ${{ env.RUNNER_TOOL_CACHE }}"
