name: Print vars
on:
  workflow_dispatch:

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Show version
        run: |
          echo "${{ vars.GITHUB_REF_NAME }}"
          echo "${{ github.ref }}"
          echo "${{ github.ref_name }}"
      - name: Print vars
        run: |
          echo "ci : ${{ ci }}"
          echo "github_action : ${{ github_action }}"
          echo "github_action_path : ${{ github_action_path }}"
          echo "github_action_repository : ${{ github_action_repository }}"
          echo "github_actions : ${{ github_actions }}"
          echo "github_actor : ${{ github_actor }}"
          echo "github_actor_id : ${{ github_actor_id }}"
          echo "github_api_url : ${{ github_api_url }}"
          echo "github_base_ref : ${{ github_base_ref }}"
          echo "github_env : ${{ github_env }}"
          echo "github_event_name : ${{ github_event_name }}"
          echo "github_event_path : ${{ github_event_path }}"
          echo "github_graphql_url : ${{ github_graphql_url }}"
          echo "github_head_ref : ${{ github_head_ref }}"
          echo "github_job : ${{ github_job }}"
          echo "github_path : ${{ github_path }}"
          echo "github_ref : ${{ github_ref }}"
          echo "github_ref_name : ${{ github_ref_name }}"
          echo "github_ref_protected : ${{ github_ref_protected }}"
          echo "github_ref_type : ${{ github_ref_type }}"
          echo "github_repository : ${{ github_repository }}"
          echo "github_repository_id : ${{ github_repository_id }}"
          echo "github_repository_owner : ${{ github_repository_owner }}"
          echo "github_repository_owner_id : ${{ github_repository_owner_id }}"
          echo "github_retention_days : ${{ github_retention_days }}"
          echo "github_run_attempt : ${{ github_run_attempt }}"
          echo "github_run_id : ${{ github_run_id }}"
          echo "github_run_number : ${{ github_run_number }}"
          echo "github_server_url : ${{ github_server_url }}"
          echo "github_sha : ${{ github_sha }}"
          echo "github_step_summary : ${{ github_step_summary }}"
          echo "github_workflow : ${{ github_workflow }}"
          echo "github_workflow_ref : ${{ github_workflow_ref }}"
          echo "github_workflow_sha : ${{ github_workflow_sha }}"
          echo "github_workspace : ${{ github_workspace }}"
          echo "runner_arch : ${{ runner_arch }}"
          echo "runner_debug : ${{ runner_debug }}"
          echo "runner_name : ${{ runner_name }}"
          echo "runner_os : ${{ runner_os }}"
          echo "runner_temp : ${{ runner_temp }}"
          echo "runner_tool_cache : ${{ runner_tool_cache }}"
