name: Print vars
on:
  workflow_dispatch:

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Show version
        run: |
          echo "${{ vars.GITHUB_REF_NAME }}"
          echo "${{ github.ref }}"
          echo "${{ github.ref_name }}"
      - name: Print vars
        run: |
          echo "github.ci : ${{ github.ci }}"
          echo "github.action : ${{ github.action }}"
          echo "github.action_path : ${{ github.action_path }}"
          echo "github.action_repository : ${{ github.action_repository }}"
          echo "github.actions : ${{ github.actions }}"
          echo "github.actor : ${{ github.actor }}"
          echo "github.actor_id : ${{ github.actor_id }}"
          echo "github.api_url : ${{ github.api_url }}"
          echo "github.base_ref : ${{ github.base_ref }}"
          echo "github.env : ${{ github.env }}"
          echo "github.event_name : ${{ github.event_name }}"
          echo "github.event_path : ${{ github.event_path }}"
          echo "github.graphql_url : ${{ github.graphql_url }}"
          echo "github.head_ref : ${{ github.head_ref }}"
          echo "github.job : ${{ github.job }}"
          echo "github.path : ${{ github.path }}"
          echo "github.ref : ${{ github.ref }}"
          echo "github.ref_name : ${{ github.ref_name }}"
          echo "github.ref_protected : ${{ github.ref_protected }}"
          echo "github.ref_type : ${{ github.ref_type }}"
          echo "github.repository : ${{ github.repository }}"
          echo "github.repository_id : ${{ github.repository_id }}"
          echo "github.repository_owner : ${{ github.repository_owner }}"
          echo "github.repository_owner_id : ${{ github.repository_owner_id }}"
          echo "github.retention_days : ${{ github.retention_days }}"
          echo "github.run_attempt : ${{ github.run_attempt }}"
          echo "github.run_id : ${{ github.run_id }}"
          echo "github.run_number : ${{ github.run_number }}"
          echo "github.server_url : ${{ github.server_url }}"
          echo "github.sha : ${{ github.sha }}"
          echo "github.step_summary : ${{ github.step_summary }}"
          echo "github.workflow : ${{ github.workflow }}"
          echo "github.workflow_ref : ${{ github.workflow_ref }}"
          echo "github.workflow_sha : ${{ github.workflow_sha }}"
          echo "github.workspace : ${{ github.workspace }}"
          echo "runner_arch : ${{ runner_arch }}"
          echo "runner_debug : ${{ runner_debug }}"
          echo "runner_name : ${{ runner_name }}"
          echo "runner_os : ${{ runner_os }}"
          echo "runner_temp : ${{ runner_temp }}"
          echo "runner_tool_cache : ${{ runner_tool_cache }}"
